# Generated by Django 3.1.2 on 2020-10-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='first_name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='email',
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_name',
        ),
    ]
