# Generated by Django 3.1.2 on 2020-10-13 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0003_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Who', models.CharField(max_length=60)),
                ('Occassion', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('details_image', models.ImageField(upload_to='category/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fotos.category')),
                ('location', models.ManyToManyField(to='fotos.location')),
            ],
        ),
    ]
