# Generated by Django 3.1.2 on 2020-10-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0004_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('gallery_image', models.ImageField(null=True, upload_to='gallery/')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='type',
            new_name='category',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fotos.category'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fotos.location'),
        ),
    ]
